spring:
  profiles:
    active: dev
  application:
    name: business
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart: # 开启 multipart 上传功能
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
server:
  servlet:
    session: #session生命周期
      timeout: 30m
  tomcat:
    uri-encoding: utf-8
    max-http-form-post-size: -1
  compression:
    enabled: true
    mime-types: application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain
    min-response-size: 1024
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '业务接口'
      paths-to-match: '/**'
      packages-to-scan: com.fc.fcbase.business
    - group: 'data基础数据接口'
      paths-to-match: '/**'
      packages-to-scan: com.fc.fcbase.basicapi
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn