<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>LX.FrameWork.SystemManager</AssemblyTitle>
    <Product>LX.FrameWork.SystemManager</Product>
    <Copyright>Copyright ©  2025</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LX.Commons\LX.Commons.csproj" />
    <ProjectReference Include="..\LX.FrameWork.DataModels\LX.FrameWork.DataModels.csproj" />
    <ProjectReference Include="..\LX.WebCommons\LX.WebCommons.csproj" />
    <ProjectReference Include="..\Sys.DataBase\Sys.DataBase.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>