<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LX.Commons\LX.Commons.csproj" />
    <ProjectReference Include="..\LX.FrameWork.DataModels\LX.FrameWork.DataModels.csproj" />
    <ProjectReference Include="..\LX.FrameWork.SystemManager\LX.FrameWork.SystemManager.csproj" />
    <ProjectReference Include="..\LX.WebCommons\LX.WebCommons.csproj" />
    <ProjectReference Include="..\Sys.DataBase\Sys.DataBase.csproj" />
  </ItemGroup>

</Project>
